---
name: build container
env:
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
  IMAGE_NAME: spilo-builder
  ARCHS: amd64,arm64

on:
  push:
    paths:
    - Containerfile.*
  workflow_dispatch:

jobs:
  build:
    name: build image
    runs-on: ubuntu-latest
    steps:
    - name: clone
      uses: actions/checkout@v3

    - name: log into registry
      uses: redhat-actions/podman-login@v1
      with:
        registry: ${{ env.IMAGE_REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ github.token }}

    - name: set up qemu for multi-arch
      run: |
        sudo apt-get update
        sudo apt-get install -y qemu-user-static
      if: ${{ env.ARCHS != 'amd64' }}

    - name: buildah
      id: build-image
      uses: redhat-actions/buildah-build@v2
      with:
        image: ${{ env.IMAGE_NAME }}
        tags: latest
        archs: ${{ env.ARCHS }}
        oci: true
        containerfiles: ./Containerfile.spilo-builder

    - name: push to registry
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-image.outputs.image }}
        tags: ${{ steps.build-image.outputs.tags }}
        registry: ${{ env.IMAGE_REGISTRY }}
