---
name: build build container
env:
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
  IMAGE_NAME: builder
  ARCHS: amd64

on:
  push:
    paths:
    - Containerfile.*
  workflow_dispatch:

jobs:
  build:
    name: build image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        postgres: ["17", "16"]
    steps:
    - name: clone
      uses: actions/checkout@v4

    - name: log into registry
      uses: redhat-actions/podman-login@v1
      with:
        registry: ${{ env.IMAGE_REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ github.token }}

    - name: buildah
      id: build-image
      uses: redhat-actions/buildah-build@v2
      with:
        image: ${{ env.IMAGE_NAME }}
        tags: ${{ matrix.postgres }}
        archs: ${{ env.ARCHS }}
        build-args: PG_MAJOR=${{ matrix.postgres }}
        oci: true
        containerfiles: ./Containerfile.builder

    - name: push to registry
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-image.outputs.image }}
        tags: ${{ steps.build-image.outputs.tags }}
        registry: ${{ env.IMAGE_REGISTRY }}
