---
name: package with latest hydra release built

env:
  upstream_repo_owner: hydradatabase
  upstream_repo_repo: hydra

on:
  workflow_dispatch:
  # disable for now
  #schedule:
  #- cron: '56 0 * * *' # daily

jobs:
  info:
    name: Get info on latest upstream and built package
    runs-on: ubuntu-latest
    outputs:
      upstream_version: ${{ steps.get_latest_package.outputs.result }}
    steps:
    - name: Get latest package release
      id: get_latest_package
      uses: actions/github-script@v6
      with:
        retries: 3
        result-encoding: string
        script: |
          return await github.rest.repos.getLatestRelease({
            owner: "${{ env.upstream_repo_owner }}",
            repo: "${{ env.upstream_repo_repo }}"
          }).then(r => r.data.tag_name)

  build:
    name: build new packages
    needs: [info]
    #if: ${{ ! contains(needs.image_tags.outputs.packages, needs.info.outputs.upstream_version) }}
    strategy:
      matrix:
        postgres: ["15", "16", "17"]
        box:
          - { runner: ubuntu-latest, arch: amd64 }
          #- { runner: arm-runner, arch: arm64 }

    runs-on: ${{ matrix.box.runner }}
    container:
      image: ghcr.io/${{ github.repository_owner }}/spilo-builder
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v4
      with:
        repository: ${{ env.upstream_repo_owner }}/${{ env.upstream_repo_repo }}
        ref: ${{ needs.info.outputs.upstream_version }}

    - name: make
      run: |
        cd columnar
        PATH=/usr/lib/postgresql/${{ matrix.postgres }}/bin:$PATH
        ./configure
        make
        
    - name: make install
      run: |
        cd columnar
        PATH=/usr/lib/postgresql/${{ matrix.postgres }}/bin:$PATH
        make DESTDIR=$PWD/destdir install

    - name: create debian packages
      run: |
        set -x
        extension_name="columnar"
        extension_version="${{ needs.info.outputs.upstream_version }}"
        deb_version="${extension_version/v/}"
        package_dir="$PWD/columnar/destdir"

        mkdir -p ${package_dir}/DEBIAN
        cat <<EOF > "${package_dir}/DEBIAN/control"
        Package: $extension_name-pg${{ matrix.postgres}}
        Version: $deb_version
        Section: database
        Priority: optional
        Architecture: ${{ matrix.box.arch }}
        Maintainer: Tobias Florek <me@ibotty.net>
        Description: ${{ env.upstream_repo_owner }} $extension_name PostgreSQL extension
        EOF

        # Create deb package
        chown -R root:root ${package_dir}
        chmod -R 00755 ${package_dir}
        dpkg-deb --build --root-owner-group "$package_dir" "$extension_name-pg${{ matrix.postgres }}.deb"

        mkdir -p deb-uploads
        find . -name *.deb -exec cp {} deb-uploads \;
        echo "found debs:"
        ls $PWD/deb-uploads -la

    - name: update apt repository
      uses: ibotty/apt-repo-update-action@v2
      with:
        debug: true
        github_token: ${{ secrets.GITHUB_TOKEN }}
        repo_supported_arch: |
          amd64
        repo_supported_distro: |
          jammy
        private_key: ${{ secrets.APT_KEY }}
        update_directory: ../deb-uploads
